import { useEffect, useState } from "react";

import {
  getNotifications,
  getUnreadNotifications,
  updateNotificationReadStatus,
} from "./api";


type NotificationItem = {
  id: number;
  title: string;
  message: string;
  notification_type: string;
  severity?: string | null;
  is_read: string;
  created_at: string;
};


function Notifications() {

  const [notifications, setNotifications] =
    useState<NotificationItem[]>([]);

  const [unreadCount, setUnreadCount] =
    useState(0);

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState("");


  useEffect(() => {
    loadNotifications();
  }, []);


  async function loadNotifications() {

    try {

      setLoading(true);
      setError("");

      const [
        notificationsData,
        unreadData,
      ] = await Promise.all([
        getNotifications(),
        getUnreadNotifications(),
      ]);

      setNotifications(
        notificationsData
      );

      setUnreadCount(
        unreadData.length
      );

    } catch (error) {

      console.error(
        "Failed to load notifications:",
        error
      );

      setError(
        error instanceof Error
          ? error.message
          : "Failed to load notifications."
      );

    } finally {

      setLoading(false);

    }
  }


  async function markAsRead(
    notificationId: number
  ) {

    try {

      const updated =
        await updateNotificationReadStatus(
          notificationId,
          true
        );

      setNotifications((current) =>
        current.map((notification) =>
          notification.id ===
          updated.id
            ? updated
            : notification
        )
      );

      setUnreadCount((current) =>
        Math.max(current - 1, 0)
      );

    } catch (error) {

      console.error(
        "Failed to mark notification as read:",
        error
      );

    }
  }


  function formatDate(
    dateString: string
  ) {

    const date =
      new Date(dateString);

    return date.toLocaleString(
      undefined,
      {
        dateStyle: "medium",
        timeStyle: "short",
      }
    );
  }


  return (

    <div className="notifications-page">

      {/* HEADER */}

      <div className="notifications-header">

        <div>

          <p className="panel-label">
            SECURITY OPERATIONS
          </p>

          <h3>
            Notification Center
          </h3>

          <p className="subtitle">
            Security alerts and system events
            generated by Inspectra.
          </p>

        </div>


        <div className="notification-header-actions">

          <span className="notification-count">

            {unreadCount}

            <small>
              unread
            </small>

          </span>


          <button
            className="secondary-button"
            onClick={loadNotifications}
            disabled={loading}
          >
            ↻ Refresh
          </button>

        </div>

      </div>


      {/* ERROR */}

      {error && (

        <div className="remediation-message">
          {error}
        </div>

      )}


      {/* CONTENT */}

      <div className="panel">

        <div className="panel-header">

          <div>

            <p className="panel-label">
              ALERT STREAM
            </p>

            <h4>
              Recent Notifications
            </h4>

          </div>


          <span className="live-badge">
            ● LIVE
          </span>

        </div>


        {loading ? (

          <div className="notification-empty">

            Loading notifications...

          </div>

        ) : notifications.length === 0 ? (

          <div className="notification-empty">

            <div className="notification-empty-icon">
              ✓
            </div>

            <strong>
              No security alerts
            </strong>

            <span>
              Inspectra has no notifications
              requiring your attention.
            </span>

          </div>

        ) : (

          <div className="notification-list">

            {notifications.map(
              (notification) => {

                const unread =
                  notification.is_read ===
                  "false";


                return (

                  <div
                    className={`notification-item ${
                      unread
                        ? "unread"
                        : ""
                    }`}
                    key={notification.id}
                  >

                    <div className="notification-icon">

                      {notification.severity ===
                      "CRITICAL"
                        ? "!"
                        : notification.severity ===
                          "HIGH"
                        ? "▲"
                        : "●"}

                    </div>


                    <div className="notification-content">

                      <div className="notification-title-row">

                        <strong>
                          {notification.title}
                        </strong>


                        {notification.severity && (

                          <span
                            className={`severity ${notification.severity.toLowerCase()}`}
                          >
                            {notification.severity}
                          </span>

                        )}

                      </div>


                      <p>
                        {notification.message}
                      </p>


                      <small>
                        {formatDate(
                          notification.created_at
                        )}
                      </small>

                    </div>


                    {unread && (

                      <button
                        className="notification-read-button"
                        onClick={() =>
                          markAsRead(
                            notification.id
                          )
                        }
                      >
                        Mark as read
                      </button>

                    )}

                  </div>

                );

              }
            )}

          </div>

        )}

      </div>

    </div>

  );
}


export default Notifications;